name: Build MAUI Windows App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'ga'

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MAUI Windows App
        run: dotnet build -c Release -f net9.0-windows10.0.19041.0 --self-contained
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maui-windows-build
          path: D:\a\UMD2MKV\UMD2MKV\UMD2MKV\bin\Release\net9.0-windows10.0.19041.0\win10-x64\*
