name: Build MAUI Windows App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache .NET workloads and NuGet
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'ga'

      - name: Install only MAUI Windows workload
        run: dotnet workload install maui-windows

      - name: Restore Windows-specific target only
        run: >
          dotnet restore UMD2MKV/UMD2MKV.csproj 
          -r win10-x64 
          -f net9.0-windows10.0.19041.0

      - name: Publish MAUI Windows App (Self-contained)
        run: >
          dotnet publish UMD2MKV/UMD2MKV.csproj 
          -c Release 
          -f net9.0-windows10.0.19041.0 
          -r win10-x64 
          --self-contained true 
          --no-restore 
          /p:PublishSingleFile=true 
          /p:IncludeAllContentForSelfExtract=true

      - name: Clean up unneeded files from publish folder
        run: |
          $publishDir = Get-ChildItem -Path UMD2MKV\bin\Release\net9.0-windows10.0.19041.0\win10-x64 -Directory -Filter "publish" | Select-Object -First 1
          Get-ChildItem -Path $publishDir.FullName -Include *.pdb,*.xml,*.json -Recurse | Remove-Item -Force

      - name: Create ZIP of Published App
        run: |
          $publishDir = Get-ChildItem -Path UMD2MKV\bin\Release\net9.0-windows10.0.19041.0\win10-x64 -Directory -Filter "publish" | Select-Object -First 1
          Compress-Archive -Path "$($publishDir.FullName)\*" -DestinationPath "${{ github.workspace }}\maui-windows-publish.zip"

      - name: Upload Published App ZIP
        uses: actions/upload-artifact@v4
        with:
          name: maui-windows-publish
          path: maui-windows-publish.zip
